version: "3.4"

services:
  sqlserver:
    container_name: sqlserver
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    ports:
      - "1433:1433"

volumes:
    sqlserver: